### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by maxlehot1234** [coco5843/ProdigygadgetTitanium#1]
Hi I just found few bugs with your plugin.

If I disable the moods and reload the plugin. The moods will continue to be available :(

If I disable the 3D  selector and open the GUI and click previous, I see this in the console:
https://pastebin.com/LZhZGBRj

Any way to fix this to prevent any future console spam?

Thank you

**Comment by coco5843** [comment]
This is a problem with perworldplugin
