### ISSUE TITLE
Strange error when click on a 3D cosmetic

### ISSUE THREAD

**Issue by BokiP22** [coco5843/ProdigygadgetTitanium#3]
Hi,
I'm saying the plugin has always worked, but today it has stopped and I do not understand why ...
When I click on a cosmetic the server kick me with this error:
![console](https://user-images.githubusercontent.com/12722102/27511837-841f5b7c-592e-11e7-9602-d393fc933c96.png)
![kick](https://user-images.githubusercontent.com/12722102/27511838-8420386c-592e-11e7-9bd0-9cdf9edb54c9.png)

The plugin always worked before this problem.
Any solution?

**Comment by coco5843** [comment]
do you have libsdisguise ?

**Comment by BokiP22** [comment]
Yes v9.1.2
