### ISSUE TITLE
MC Client Crash

### ISSUE THREAD

**Issue by Minners** [coco5843/ProdigygadgetTitanium#5]
Hello,
Minecraft Crashes when a Player rightclick a Morphed Player (any Morph's)

[Server Info]

Version:
git-TacoSpigot-"af15657" (MC: 1.9.4) (Implementing API version 1.9.4-R0.1)

Plugins:
- CloudNet-API
- ProdigyGadget
- PartyAndFriendsGUI
- Top
- ViaVersion
- IPWhitelist
- CustomGUI
- BungeePerms
- ProtocolLib

[Crash Info's]

The game crashed whilst unexpected error
Error: java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Boolean

Crash Report - https://hastebin.com/ecilucufag.php
Latest Log - https://hastebin.com/wasebififo.sql

**Comment by coco5843** [comment]
thank you, this bug does not exist if you're using 1.11.2, do not know why, I will check

**Comment by coco5843** [comment]
Okay, fixed :) wait for the next update
